version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  
  worker:
    image: pycel
    build: .
    command:
      - 'celery'
      - '-A'
      - 'pycel'
      - 'worker'
      - '-l'
      - 'INFO'
    env_file:
      - .env
    depends_on:
      - redis
