version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  
  worker:
    image: pycel
    build: .
    command:
      - 'celery'
      - '-A'
      - 'pycel'
      - 'worker'
      - '-l'
      - 'INFO'
    env_file:
      - .env
    depends_on:
      - redis

  scheduler:
    image: pycel
    build: .
    command:
      - 'celery'
      - '-A'
      - 'pycel'
      - 'beat'
      - '-l'
      - 'DEBUG'
    env_file:
      - .env
    depends_on:
      - redis

  flower:
    image: pycel
    build: .
    command:
      - 'celery'
      - '-A'
      - 'pycel'
      - 'flower'
      - '--port=5000'
      - '--address=0.0.0.0'
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - redis
